apiVersion: v2
version: 0.1.10
appVersion:

name: frontend
description: "Simple frontend app template."
home: https://github.com/NIKKITOD
sources:
- https://github.com/NIKKITOD/helm-charts

maintainers:
- name: Nikita Slepnev
  email: slepnevns@gmail.com