nameOverride: ""
fullnameOverride: ""

common:
  component: "frontend"

image:
  registry: docker.io
  repository: nikitod/test-react-for-helm
  tag: latest
  pullPolicy: IfNotPresent
  debug: false

ports:

config:

secrets: