apiVersion: v2
version: 0.1.6
appVersion: "0.1.2"

name: app-stack
description: "Simple stack chart template."
home: https://github.com/NIKKITOD
sources:
- https://github.com/NIKKITOD/helm-charts

home: https://github.com/NIKKITOD/helm-charts
maintainers:
- name: NIKKITOD
  email: slepnevsns@gmail.com

dependencies:
- name: "backend"
  condition: backend.enabled
  version: "0.1.4"
  repository: "https://nikkitod.github.io/helm-charts/"
- name: "frontend"
  condition: frontend.enabled
  version: "0.1.2"
  repository: "https://nikkitod.github.io/helm-charts/"