apiVersion: v1
kind: ConfigMap
metadata:
  name:  {{ include "frontend.fullname" . }}-config
  namespace: {{ .Release.Namespace | quote }}
  labels:
{{ include "frontend.labels" . | indent 4 }}    
data:
  SOME_DATA: {{ .Values.config.some_data }}