{{- if .Values.config }}
apiVersion: v1
kind: ConfigMap
metadata:
  name:  {{ include "frontend.fullname" . }}-config
  namespace: {{ .Release.Namespace | quote }}
  labels:
{{ include "frontend.labels" . | indent 4 }}    
data:
{{- range .Values.config }}
  {{ .name | quote }}: {{ .value | b64enc }} 
{{- end }}
{{- end }}