apiVersion: v1
kind: Secret
metadata:
  name: {{ include "frontend.fullname" . }}-secret
  namespace: {{ .Release.Namespace | quote }}
  labels:
{{ include "frontend.labels" . | indent 4 }}
data:
  SOME_SECRET: {{ .Values.secret.some_secret | b64enc }}
type: Opaque