kind: Service
apiVersion: v1
metadata:
  name:  {{ include "frontend.fullname" . }}-service
  namespace: {{ .Release.Namespace | quote }}
  labels:
{{ include "frontend.labels" . | indent 4 }}    
spec:
  selector:
{{ include "frontend.selectorLabels" . | indent 4 }}
  type:  NodePort
  ports:
    - name:  http
      port:  {{ default 3000 .Values.common.port }}
      targetPort:  {{ default 3000 .Values.common.containerPort }}