kind: Service
apiVersion: v1
metadata:
  name:  {{ include "frontend.fullname" . }}-service
  namespace: {{ .Release.Namespace | quote }}
  labels:
{{ include "frontend.labels" . | indent 4 }}    
spec:
  selector:
{{ include "frontend.selectorLabels" . | indent 4 }}
  type:  NodePort
  ports:
    {{- range .Values.common.ports }}
    - name:  {{ default "http" .name }}
      port:  {{ default 80 .port}}
      targetPort:  {{ default 80 .port }}
    {{- end }}