apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "backend.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
{{ include "backend.labels" . | indent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
{{ include "backend.selectorLabels" . | indent 6 }}
  template:
    metadata:
      labels:
{{ include "backend.selectorLabels" . | indent 8 }}
    spec:
      containers:
      - name: {{ include "backend.fullname" . }}
        image: "{{ default .Values.image.registry }}/{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        ports:
        {{- if .Values.ports }}
        {{- range .Values.ports }}
        - name: {{ default "http" .name }}
          containerPort: {{ default 80 .port }}
        {{- end }}
        {{- end }}
        volumeMounts:
          {{- if .Values.volumes }}   
          {{- range .Values.volumes }}
          - mountPath: {{ .mountPath }}
            name: {{ include "backend.fullname" $ }}-{{ .name }}-volume
          {{- end }}
          {{- end }}
          {{- if .Values.nginx.enabled }}
          - mountPath: /etc/nginx/nginx.conf
            name: {{ include "backend.fullname" . }}-nginx-config-volume
            subPath: nginx.conf
          {{- end }}
      initContainers:
        {{- if .Values.volumes }}
        {{- range .Values.volumes }}
        - name: {{ .name }}
          image: "{{ $.Values.image.registry}}/{{ $.Values.image.repository}}:{{ $.Values.image.tag }}"
          imagePullPolicy: {{ default "" $.Values.image.pullPolicy | quote }}
          command: {{ .command }}
          volumeMounts:
            - mountPath: {{ .initMountPath }}
              name: {{ include "backend.fullname" $ }}-{{ .name }}-volume
        {{- end }}
        {{- end }}
      volumes:
        {{- if .Values.volumes }}
        {{- range .Values.volumes }}
        - name: {{ include "backend.fullname" $ }}-{{ .name }}-volume
          persistentVolumeClaim:
            claimName: {{ include "backend.fullname" $ }}-{{ .name }}-volume
        {{- end }}
        {{- end }}
        {{- if .Values.nginx.enabled }}
        - configMap:
            defaultMode: 256
            name: {{ include "backend.fullname" . }}-nginx-config
            optional: false
          name: {{ include "backend.fullname" . }}-nginx-config-volume
        {{- end }}