kind: Service
apiVersion: v1
metadata:
  name:  {{ include "backend.fullname" . }}-service
  namespace: {{ .Release.Namespace | quote }}
  labels:
{{ include "backend.labels" . | indent 4 }}    
spec:
  selector:
{{ include "backend.selectorLabels" . | indent 4 }}
  type:  NodePort
  ports:
    {{- range .Values.common.ports }}
    - name: {{ default "http" .name }}
      port: {{ default 80 .port}}
      targetPort: {{ default 80 .port }}
    {{- end }}