kind: Service
apiVersion: v1
metadata:
  name:  {{ include "backend.fullname" . }}-service
  namespace: {{ .Release.Namespace | quote }}
  labels:
{{ include "backend.labels" . | indent 4 }}    
spec:
  selector:
{{ include "backend.selectorLabels" . | indent 4 }}
  type:  NodePort
  ports:
    - name:  http
      port:  {{ default 5000 .Values.common.port}}
      targetPort:  {{ default 500 .Values.common.containerPort }}
    # - name:  php-fpm
    #   port:  9000
    #   targetPort:  9000