{{- if .Values.volumes }}
{{- range .Values.volumes }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "backend.fullname" $ }}-{{ .name }}-volume
  labels:
{{ include "backend.labels" $ | indent 4 }}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ default "1Gi" .size }}
  storageClassName: {{ default "hostpath" .storageClass }}
{{- end }}
{{- end }}

{{- if .Values.nginx.enabled }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "backend.fullname" . }}-nginx-volume
  labels:
{{ include "backend.labels" . | indent 4 }}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ default "1Gi" }}
  storageClassName: "hostpath"
{{- end }}